package parkir;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;
public class NewJFrame extends javax.swing.JFrame {
    SimpleDateFormat d = new SimpleDateFormat("d-MMM-yyy");
    Calendar c = Calendar.getInstance();
    
    String plat []= new String[8];
    String tanggal []=new String [8];
    String waktu []= new String [8];
    String waktu2 []= new String [8];
    String w;
   
    public NewJFrame() {
        initComponents();
        setTitle("Program Parkir");
    }
    private void UpdateClock() {
        c.setTimeInMillis(System.currentTimeMillis());
        int jam = c.get(Calendar.HOUR_OF_DAY);
        int menit = c.get(Calendar.MINUTE);
        int detik = c.get(Calendar.SECOND);
        w= String.valueOf(jam+":"+menit+":"+detik);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Masuka = new javax.swing.JButton();
        TampilanData = new javax.swing.JButton();
        InputPlat = new javax.swing.JTextField();
        Masukb = new javax.swing.JButton();
        Masukc = new javax.swing.JButton();
        Masukd = new javax.swing.JButton();
        Masuke = new javax.swing.JButton();
        Masukf = new javax.swing.JButton();
        Masukg = new javax.swing.JButton();
        Masukh = new javax.swing.JButton();
        Keluara = new javax.swing.JButton();
        Keluarb = new javax.swing.JButton();
        Keluarc = new javax.swing.JButton();
        Keluard = new javax.swing.JButton();
        Keluare = new javax.swing.JButton();
        Keluarf = new javax.swing.JButton();
        Keluarg = new javax.swing.JButton();
        Keluarh = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nomor Plat :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Sistem Parkir");

        Masuka.setText("Masuk");
        Masuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukaActionPerformed(evt);
            }
        });

        TampilanData.setText("Tampilkan Data");
        TampilanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilanDataActionPerformed(evt);
            }
        });

        InputPlat.setText("Plat Nomor ...");
        InputPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPlatActionPerformed(evt);
            }
        });

        Masukb.setText("Masuk");
        Masukb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukbActionPerformed(evt);
            }
        });

        Masukc.setText("Masuk");
        Masukc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukcActionPerformed(evt);
            }
        });

        Masukd.setText("Masuk");
        Masukd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukdActionPerformed(evt);
            }
        });

        Masuke.setText("Masuk");
        Masuke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukeActionPerformed(evt);
            }
        });

        Masukf.setText("Masuk");
        Masukf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukfActionPerformed(evt);
            }
        });

        Masukg.setText("Masuk");
        Masukg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukgActionPerformed(evt);
            }
        });

        Masukh.setText("Masuk");
        Masukh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukhActionPerformed(evt);
            }
        });

        Keluara.setText("Keluar");
        Keluara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluaraActionPerformed(evt);
            }
        });

        Keluarb.setText("Keluar");
        Keluarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarbActionPerformed(evt);
            }
        });

        Keluarc.setText("Keluar");
        Keluarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarcActionPerformed(evt);
            }
        });

        Keluard.setText("Keluar");
        Keluard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluardActionPerformed(evt);
            }
        });

        Keluare.setText("Keluar");
        Keluare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluareActionPerformed(evt);
            }
        });

        Keluarf.setText("Keluar");
        Keluarf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarfActionPerformed(evt);
            }
        });

        Keluarg.setText("Keluar");
        Keluarg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluargActionPerformed(evt);
            }
        });

        Keluarh.setText("Keluar");
        Keluarh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TampilanData))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Keluara, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Keluarb, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Masuke, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Keluare, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Keluarf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Masukf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Masuka, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(Masukb, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Keluarg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Masukg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Keluarc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Masukc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Keluarh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Masukh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Keluard, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Masukd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TampilanData))
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Masuka, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Masukb, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Masukc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Masukd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Keluarb, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Keluara, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Masukf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Masuke, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Keluarf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Keluare, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Keluarc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Keluard, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Masukh, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Masukg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Keluarh, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Keluarg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TampilanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilanDataActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
        jDialog1.setSize(450,340);
        jTextArea1.setText("Area 1\n"+"No Plat  : "+plat[0]+"\n"+"Tanggal : "+tanggal[0]+"\nWaktu Masuk : "+waktu[0]+"\n\n"
                           +"Area 2\n"+"No Plat : "+plat[1]+"\n"+"Tanggal : "+tanggal[1]+"\nWaktu Masuk : "+waktu[1]+"\n\n"
                           +"Area 3\n"+"No Plat : "+plat[2]+"\n"+"Tanggal : "+tanggal[2]+"\nWaktu Masuk : "+waktu[2]+"\n\n"
                           +"Area 4\n"+"No Plat : "+plat[3]+"\n"+"Tanggal : "+tanggal[3]+"\nWaktu Masuk : "+waktu[3]+"\n\n"
                           +"Area 5\n"+"No Plat : "+plat[4]+"\n"+"Tanggal : "+tanggal[4]+"\nWaktu Masuk : "+waktu[4]+"\n\n"
                           +"Area 6\n"+"No Plat : "+plat[5]+"\n"+"Tanggal : "+tanggal[5]+"\nWaktu Masuk : "+waktu[5]+"\n\n"
                           +"Area 7\n"+"No Plat : "+plat[6]+"\n"+"Tanggal : "+tanggal[6]+"\nWaktu Masuk : "+waktu[6]+"\n\n"
                           +"Area 8\n"+"No Plat : "+plat[7]+"\n"+"Tanggal : "+tanggal[7]+"\nWaktu Masuk : "+waktu[7]+"\n\n");
        jTextArea2.setText("Area 1\n"+"No Plat  : "+plat[0]+"\n"+"Tanggal : "+tanggal[0]+"\nWaktu Keluar : "+waktu2[0]+"\n\n"
                           +"Area 2\n"+"No Plat : "+plat[1]+"\n"+"Tanggal : "+tanggal[1]+"\nWaktu Keluar : "+waktu2[1]+"\n\n"
                           +"Area 3\n"+"No Plat : "+plat[2]+"\n"+"Tanggal : "+tanggal[2]+"\nWaktu Keluar : "+waktu2[2]+"\n\n"
                           +"Area 4\n"+"No Plat : "+plat[3]+"\n"+"Tanggal : "+tanggal[3]+"\nWaktu Keluar : "+waktu2[3]+"\n\n"
                           +"Area 5\n"+"No Plat : "+plat[4]+"\n"+"Tanggal : "+tanggal[4]+"\nWaktu Keluar : "+waktu2[4]+"\n\n"
                           +"Area 6\n"+"No Plat : "+plat[5]+"\n"+"Tanggal : "+tanggal[5]+"\nWaktu Keluar : "+waktu2[5]+"\n\n"
                           +"Area 7\n"+"No Plat : "+plat[6]+"\n"+"Tanggal : "+tanggal[6]+"\nWaktu Keluar : "+waktu2[6]+"\n\n"
                           +"Area 8\n"+"No Plat : "+plat[7]+"\n"+"Tanggal : "+tanggal[7]+"\nWaktu Keluar : "+waktu2[7]+"\n\n");
        
       
    }//GEN-LAST:event_TampilanDataActionPerformed

    private void InputPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPlatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_InputPlatActionPerformed

    private void MasukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukaActionPerformed
        // TODO add your handling code here:
        
        plat[0]=InputPlat.getText();
        tanggal[0]=d.format(c.getTime());
        UpdateClock();
        waktu[0]=w;
        Masuka.setVisible(false);
        Keluara.setVisible(true);
    }//GEN-LAST:event_MasukaActionPerformed

    private void MasukbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukbActionPerformed
        // TODO add your handling code here:
       plat[1]=InputPlat.getText();
       tanggal[1]=d.format(c.getTime());
       UpdateClock();
       waktu[1]=w;
       Masukb.setVisible(false);
    }//GEN-LAST:event_MasukbActionPerformed

    private void MasukcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukcActionPerformed
        // TODO add your handling code here:
        plat[2]=InputPlat.getText();
        tanggal[2]=d.format(c.getTime());
        UpdateClock();
        waktu[2]=w;
        Masukc.setVisible(false);
    }//GEN-LAST:event_MasukcActionPerformed

    private void MasukdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukdActionPerformed
        // TODO add your handling code here:
        plat[3]=InputPlat.getText();
        tanggal[3]=d.format(c.getTime());
        UpdateClock();
        waktu[3]=w;
        Masukd.setVisible(false);
    }//GEN-LAST:event_MasukdActionPerformed

    private void MasukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukeActionPerformed
        // TODO add your handling code here:
        plat[4]=InputPlat.getText();
        tanggal[4]=d.format(c.getTime());
        UpdateClock();
        waktu[4]=w;
        Masuke.setVisible(false);
    }//GEN-LAST:event_MasukeActionPerformed

    private void MasukfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukfActionPerformed
        // TODO add your handling code here:
        plat[5]=InputPlat.getText();
        tanggal[5]=d.format(c.getTime());
        UpdateClock();
        waktu[5]=w;
        Masukf.setVisible(false);
    }//GEN-LAST:event_MasukfActionPerformed

    private void MasukgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukgActionPerformed
        // TODO add your handling code here:
        plat[6]=InputPlat.getText();
        tanggal[6]=d.format(c.getTime());
        UpdateClock();
        waktu[6]=w;
        Masukg.setVisible(false);
    }//GEN-LAST:event_MasukgActionPerformed

    private void MasukhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukhActionPerformed
        // TODO add your handling code here:
        plat[7]=InputPlat.getText();
        tanggal[7]=d.format(c.getTime());
        UpdateClock();
        waktu[7]=w;
        Masukh.setVisible(false);
    }//GEN-LAST:event_MasukhActionPerformed

    private void KeluaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluaraActionPerformed
        // TODO add your handling code here:
         plat[0]=InputPlat.getText();
         tanggal[0]=d.format(c.getTime());
         UpdateClock();
         waktu2[0]=w;
         Masuka.setVisible(true);
         Keluara.setVisible(false);
    }//GEN-LAST:event_KeluaraActionPerformed

    private void KeluarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarbActionPerformed
        // TODO add your handling code here:
        plat[1]=InputPlat.getText();
        tanggal[1]=d.format(c.getTime());
        UpdateClock();
        waktu2[1]=w;
        Masukb.setVisible(true);
        Keluarb.setVisible(false);
    }//GEN-LAST:event_KeluarbActionPerformed

    private void KeluarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarcActionPerformed
        // TODO add your handling code here:
        plat[2]=InputPlat.getText();
        tanggal[2]=d.format(c.getTime());
        UpdateClock();
        waktu2[2]=w;
        Masukc.setVisible(true);
        Keluarc.setVisible(false);
    }//GEN-LAST:event_KeluarcActionPerformed

    private void KeluardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluardActionPerformed
        // TODO add your handling code here:
        plat[3]=InputPlat.getText();
        tanggal[3]=d.format(c.getTime());
        UpdateClock();
        waktu2[3]=w;
        Masukd.setVisible(true);
        Keluard.setVisible(false);
    }//GEN-LAST:event_KeluardActionPerformed

    private void KeluareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluareActionPerformed
        // TODO add your handling code here:
        plat[4]=InputPlat.getText();
        tanggal[4]=d.format(c.getTime());
        UpdateClock();
        waktu2[4]=w;
        Masuke.setVisible(true);
        Keluare.setVisible(false);
    }//GEN-LAST:event_KeluareActionPerformed

    private void KeluarfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarfActionPerformed
        // TODO add your handling code here:
        plat[5]=InputPlat.getText();
        tanggal[5]=d.format(c.getTime());
        UpdateClock();
        waktu2[5]=w;
        Masukf.setVisible(true);
        Keluarf.setVisible(false);
    }//GEN-LAST:event_KeluarfActionPerformed

    private void KeluargActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluargActionPerformed
        // TODO add your handling code here:
         plat[6]=InputPlat.getText();
         tanggal[6]=d.format(c.getTime());
        UpdateClock();
        waktu2[6]=w;
        Masukg.setVisible(true);
        Keluarg.setVisible(false);
    }//GEN-LAST:event_KeluargActionPerformed

    private void KeluarhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarhActionPerformed
        // TODO add your handling code here:
        plat[7]=InputPlat.getText();
        tanggal[7]=d.format(c.getTime());
        UpdateClock();
        waktu2[7]=w;
        Masukh.setVisible(true);
        Keluarh.setVisible(false);
    }//GEN-LAST:event_KeluarhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputPlat;
    private javax.swing.JButton Keluara;
    private javax.swing.JButton Keluarb;
    private javax.swing.JButton Keluarc;
    private javax.swing.JButton Keluard;
    private javax.swing.JButton Keluare;
    private javax.swing.JButton Keluarf;
    private javax.swing.JButton Keluarg;
    private javax.swing.JButton Keluarh;
    private javax.swing.JButton Masuka;
    private javax.swing.JButton Masukb;
    private javax.swing.JButton Masukc;
    private javax.swing.JButton Masukd;
    private javax.swing.JButton Masuke;
    private javax.swing.JButton Masukf;
    private javax.swing.JButton Masukg;
    private javax.swing.JButton Masukh;
    private javax.swing.JButton TampilanData;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}