/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lahanparkir;

/**
 *
 * @author Lenovo
 */
import java.awt.BorderLayout;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
public class lahanlagi extends javax.swing.JFrame {
    String lahan[]={"","","","","","","",""};
    String tanggal[]=new String[8];
    String jam[]=new String[8];
    String keluar[]=new String[8];
    Object data[][]=new Object[8][4];
    Calendar kalender = Calendar.getInstance();
    String kolom[]={"NO.PLAT","TANGGAL MASUK","JAM MASUK","TANGGAL DAN JAM KELUAR"};
    
    SimpleDateFormat date = new SimpleDateFormat("d-MMM-yyy");
    SimpleDateFormat waktu = new SimpleDateFormat("HH:mm:ss");
    public lahanlagi() {
        initComponents();
        btnM1.addActionListener(new action());
        btnM2.addActionListener(new action());
        btnM3.addActionListener(new action());
        btnM4.addActionListener(new action());
        btnM5.addActionListener(new action());
        btnM6.addActionListener(new action());
        btnM7.addActionListener(new action());
        btnM8.addActionListener(new action());
        btnK1.addActionListener(new action());
        btnK1.setEnabled(false);
        btnK2.addActionListener(new action());
        btnK2.setEnabled(false);
        btnK3.addActionListener(new action());
        btnK3.setEnabled(false);
        btnK4.addActionListener(new action());
        btnK4.setEnabled(false);
        btnK5.addActionListener(new action());
        btnK5.setEnabled(false);
        btnK6.addActionListener(new action());
        btnK6.setEnabled(false);
        btnK7.addActionListener(new action());
        btnK7.setEnabled(false);
        btnK8.addActionListener(new action());
        btnK8.setEnabled(false);
        jButton1.addActionListener(new action());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        noplat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnM2 = new javax.swing.JButton();
        btnK2 = new javax.swing.JButton();
        btnM1 = new javax.swing.JButton();
        btnK1 = new javax.swing.JButton();
        btnK3 = new javax.swing.JButton();
        btnM3 = new javax.swing.JButton();
        btnM4 = new javax.swing.JButton();
        btnK4 = new javax.swing.JButton();
        btnM6 = new javax.swing.JButton();
        btnK6 = new javax.swing.JButton();
        btnM5 = new javax.swing.JButton();
        btnK5 = new javax.swing.JButton();
        btnM8 = new javax.swing.JButton();
        btnK8 = new javax.swing.JButton();
        btnM7 = new javax.swing.JButton();
        btnK7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("plat nomor");

        jButton1.setText("Tampilkan Data");

        jLabel1.setText("Sistem Parkir");

        btnM2.setText("Masuk P2");

        btnK2.setText("Keluar P2");

        btnM1.setText("Masuk P1");
        btnM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM1ActionPerformed(evt);
            }
        });

        btnK1.setText("Keluar P1");

        btnK3.setText("Keluar P3");

        btnM3.setText("Masuk P3");

        btnM4.setText("Masuk P4");

        btnK4.setText("Keluar P4");

        btnM6.setText("Masuk P6");

        btnK6.setText("Keluar P6");

        btnM5.setText("Masuk P5");

        btnK5.setText("Keluar P5");

        btnM8.setText("Masuk P8");

        btnK8.setText("Keluar P8");

        btnM7.setText("Masuk P7");

        btnK7.setText("Keluar P7");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnM6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnM7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnM8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnK4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnM4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(noplat, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noplat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(2, 2, 2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnM4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnK2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnM6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnK6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnM8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnM7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnK8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM1ActionPerformed
        
    }//GEN-LAST:event_btnM1ActionPerformed

    /**
     * @param args the command line arguments
     */
    class action extends JDialog implements ActionListener{
        
        public void actionPerformed(ActionEvent e) {
            if (e.getActionCommand().equalsIgnoreCase("Masuk P1")){
                data[0][0]=noplat.getText();
                data[0][1]=date.format(kalender.getTime());
                data[0][2]=waktu.format(kalender.getTime());
                data[0][3]="";
                btnM1.setEnabled(false);
                btnK1.setEnabled(true);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Masuk P2")){
                data[1][0]=noplat.getText();
                data[1][1]=date.format(kalender.getTime());
                data[1][2]=waktu.format(kalender.getTime());
                data[1][3]="";
                btnM2.setEnabled(false);
                btnK2.setEnabled(true);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Masuk P3")){
                data[2][0]=noplat.getText();
                data[2][1]=date.format(kalender.getTime());
                data[2][2]=waktu.format(kalender.getTime());
                data[2][3]="";
                btnM3.setEnabled(false);
                btnK3.setEnabled(true);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Masuk P4")){
                data[3][0]=noplat.getText();
                data[3][1]=date.format(kalender.getTime());
                data[3][2]=waktu.format(kalender.getTime());
                data[3][3]="";
                btnM4.setEnabled(false);
                btnK4.setEnabled(true);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Masuk P5")){
                data[4][0]=noplat.getText();
                data[4][1]=date.format(kalender.getTime());
                data[4][2]=waktu.format(kalender.getTime());
                data[4][3]="";
                btnM5.setEnabled(false);
                btnK5.setEnabled(true);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Masuk P6")){
                data[5][0]=noplat.getText();
                data[5][1]=date.format(kalender.getTime());
                data[5][2]=waktu.format(kalender.getTime());
                data[5][3]="";
                btnM6.setEnabled(false);
                btnK6.setEnabled(true);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Masuk P7")){
                data[6][0]=noplat.getText();
                data[6][1]=date.format(kalender.getTime());
                data[6][2]=waktu.format(kalender.getTime());
                data[6][3]="";
                btnM7.setEnabled(false);
                btnK7.setEnabled(true);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Masuk P8")){
                data[7][0]=noplat.getText();
                data[7][1]=date.format(kalender.getTime());
                data[7][2]=waktu.format(kalender.getTime());
                data[7][3]="";
                btnM8.setEnabled(false);
                btnK8.setEnabled(true);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Keluar P1")){
                data[0][0]="";
                data[0][1]="";
                data[0][2]="";
                data[0][3]=date.format(kalender.getTime())+" "+waktu.format(kalender.getTime());
                btnM1.setEnabled(true);
                btnK1.setEnabled(false);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Keluar P2")){
                data[1][0]="";
                data[1][1]="";
                data[1][2]="";
                data[1][3]=date.format(kalender.getTime())+" "+waktu.format(kalender.getTime());
                btnM2.setEnabled(true);
                btnK2.setEnabled(false);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Keluar P3")){
                data[2][0]="";
                data[2][1]="";
                data[2][2]="";
                data[2][3]=date.format(kalender.getTime())+" "+waktu.format(kalender.getTime());
                btnM3.setEnabled(true);
                btnK3.setEnabled(false);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Keluar P4")){
                data[3][0]="";
                data[3][1]="";
                data[3][2]="";
                data[3][3]=date.format(kalender.getTime())+" "+waktu.format(kalender.getTime());
                btnM4.setEnabled(true);
                btnK4.setEnabled(false);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Keluar P5")){
                data[4][0]="";
                data[4][1]="";
                data[4][2]="";
                data[4][3]=date.format(kalender.getTime())+" "+waktu.format(kalender.getTime());
                btnM5.setEnabled(true);
                btnK5.setEnabled(false);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Keluar P6")){
                data[5][0]="";
                data[5][1]="";
                data[5][2]="";
                data[5][3]=date.format(kalender.getTime())+" "+waktu.format(kalender.getTime());
                btnM6.setEnabled(true);
                btnK6.setEnabled(false);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Keluar P7")){
                data[6][0]="";
                data[6][1]="";
                data[6][2]="";
                data[6][3]=date.format(kalender.getTime())+" "+waktu.format(kalender.getTime());
                btnM7.setEnabled(true);
                btnK7.setEnabled(false);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Keluar P8")){
                data[7][0]="";
                data[7][1]="";
                data[7][2]="";
                data[7][3]=date.format(kalender.getTime())+" "+waktu.format(kalender.getTime());
                btnM8.setEnabled(true);
                btnK8.setEnabled(false);
            }
            else if(e.getActionCommand().equalsIgnoreCase("Tampilkan Data")){
                
                JTable tabel = new JTable(data, kolom);
                add(new JScrollPane(tabel),BorderLayout.CENTER);
                setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                pack();
                setVisible(true);
                jTextField1.setText(lahan[2]);
            }
        }
    
    }
    class panel extends JDialog {
    private JTable tabel;
    private String[][] data;
    private String[] columnNames;
    public panel(String[][] data, String[] columnNames) {
        this.data = data;
        this.columnNames = columnNames;
        setLocationRelativeTo(null);
        setLayout(null);
        JTable tabel = new JTable(data, columnNames);
        tabel.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        add(new JScrollPane(tabel));
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lahanlagi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lahanlagi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lahanlagi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lahanlagi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lahanlagi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnK1;
    private javax.swing.JButton btnK2;
    private javax.swing.JButton btnK3;
    private javax.swing.JButton btnK4;
    private javax.swing.JButton btnK5;
    private javax.swing.JButton btnK6;
    private javax.swing.JButton btnK7;
    private javax.swing.JButton btnK8;
    private javax.swing.JButton btnM1;
    private javax.swing.JButton btnM2;
    private javax.swing.JButton btnM3;
    private javax.swing.JButton btnM4;
    private javax.swing.JButton btnM5;
    private javax.swing.JButton btnM6;
    private javax.swing.JButton btnM7;
    private javax.swing.JButton btnM8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField noplat;
    // End of variables declaration//GEN-END:variables
}
