/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkir;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author yudi hermawan
 */
public class Park extends javax.swing.JFrame {

    private String plat[] = new String[7];
    private String tanggal[] = new String[7];
    SimpleDateFormat d = new SimpleDateFormat("dd-MM-yyyy");
    Calendar c = Calendar.getInstance();

    public Park() {
        initComponents();

        judul = new javax.swing.JLabel();
        nomor = new javax.swing.JLabel();
        txtplat = new javax.swing.JTextField();
        tampil = new javax.swing.JButton();
        Masuk1 = new javax.swing.JButton();
        Masuk2 = new javax.swing.JButton();
        Masuk3 = new javax.swing.JButton();
        Masuk4 = new javax.swing.JButton();
        Masuk5 = new javax.swing.JButton();
        Masuk6 = new javax.swing.JButton();
        Masuk7 = new javax.swing.JButton();
        Masuk8 = new javax.swing.JButton();
        Keluar1 = new javax.swing.JButton();
        Keluar2 = new javax.swing.JButton();
        Keluar3 = new javax.swing.JButton();
        Keluar4 = new javax.swing.JButton();
        Keluar5 = new javax.swing.JButton();
        Keluar6 = new javax.swing.JButton();
        Keluar7 = new javax.swing.JButton();
        Keluar8 = new javax.swing.JButton();
        nampil = new javax.swing.JTextArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        txtplat = new javax.swing.JTextField();
        tampil = new javax.swing.JButton();
        Masuk2 = new javax.swing.JButton();
        Masuk3 = new javax.swing.JButton();
        Masuk4 = new javax.swing.JButton();
        Masuk1 = new javax.swing.JButton();
        Keluar1 = new javax.swing.JButton();
        Keluar2 = new javax.swing.JButton();
        Keluar3 = new javax.swing.JButton();
        Keluar4 = new javax.swing.JButton();
        Masuk5 = new javax.swing.JButton();
        Masuk6 = new javax.swing.JButton();
        Masuk7 = new javax.swing.JButton();
        Masuk8 = new javax.swing.JButton();
        Keluar5 = new javax.swing.JButton();
        Keluar6 = new javax.swing.JButton();
        Keluar8 = new javax.swing.JButton();
        Keluar7 = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        nomor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nampil = new javax.swing.JTextArea();

        jButton2.setText("jButton2");

        jButton5.setText("jButton5");

        jButton14.setText("jButton14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("parkir");

        txtplat.setText("Plat Nomor...");
        txtplat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplatActionPerformed(evt);
            }
        });

        tampil.setText("Tampilkan Data");
        tampil.setActionCommand("");
        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });

        Masuk2.setText("Masuk");
        Masuk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk2ActionPerformed(evt);
            }
        });

        Masuk3.setText("Masuk");
        Masuk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk3ActionPerformed(evt);
            }
        });

        Masuk4.setText("Masuk");
        Masuk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk4ActionPerformed(evt);
            }
        });

        Masuk1.setText("Masuk");
        Masuk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk1ActionPerformed(evt);
            }
        });

        Keluar1.setText("Keluar");
        Keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar1ActionPerformed(evt);
            }
        });

        Keluar2.setText("Keluar");
        Keluar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar2ActionPerformed(evt);
            }
        });

        Keluar3.setText("Keluar");
        Keluar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar3ActionPerformed(evt);
            }
        });

        Keluar4.setText("Keluar");
        Keluar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar4ActionPerformed(evt);
            }
        });

        Masuk5.setText("Masuk");
        Masuk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk5ActionPerformed(evt);
            }
        });

        Masuk6.setText("Masuk");
        Masuk6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk6ActionPerformed(evt);
            }
        });

        Masuk7.setText("Masuk");
        Masuk7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk7ActionPerformed(evt);
            }
        });

        Masuk8.setText("Masuk");
        Masuk8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk8ActionPerformed(evt);
            }
        });

        Keluar5.setText("Keluar");
        Keluar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar5ActionPerformed(evt);
            }
        });

        Keluar6.setText("Keluar");
        Keluar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar6ActionPerformed(evt);
            }
        });

        Keluar8.setText("Keluar");
        Keluar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar8ActionPerformed(evt);
            }
        });

        Keluar7.setText("Keluar");
        Keluar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keluar7ActionPerformed(evt);
            }
        });

        judul.setText("Sistem Parkir");

        nomor.setText("Nomor Plat :");

        nampil.setColumns(20);
        nampil.setRows(5);
        jScrollPane1.setViewportView(nampil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Masuk1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Keluar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Masuk5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Keluar6, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(Keluar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Masuk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Masuk6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(Keluar5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Masuk3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Keluar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Masuk7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Keluar7, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtplat, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tampil)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Masuk4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Keluar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Masuk8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Keluar8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(judul)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtplat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampil))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Masuk1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Masuk2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Masuk3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Masuk4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Keluar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Keluar2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Keluar4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Keluar3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Masuk5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Masuk6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Masuk7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Masuk8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Keluar7, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(Keluar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Keluar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Keluar8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtplatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplatActionPerformed

    }//GEN-LAST:event_txtplatActionPerformed

    private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
        nampil.setText("   \tData Parkir \n\n"
                + "\nNomor Plat " + plat[0] + " Parkir di sektor 1 pada tanggal " + tanggal[0]
                + "\nNomor Plat " + plat[1] + " Parkir di sektor 2 pada tanggal " + tanggal[1]
                + "\nNomor Plat " + plat[2] + " Parkir di sektor 3 pada tanggal " + tanggal[2]
                + "\nNomor Plat " + plat[3] + " Parkir di sektor 4 pada tanggal " + tanggal[3]
                + "\nNomor Plat " + plat[4] + " Parkir di sektor 5 pada tanggal " + tanggal[4]
                + "\nNomor Plat " + plat[5] + " Parkir di sektor 6 pada tanggal " + tanggal[5]
                + "\nNomor Plat " + plat[6] + " Parkir di sektor 7 pada tanggal " + tanggal[6]
                + "\nNomor Plat " + plat[7] + " Parkir di sektor 8 pada tanggal " + tanggal[7]
                + "\nNomor Plat " + plat[0] + " Parkir di sektor 1 telah keluar"
                + "\nNomor Plat " + plat[1] + " Parkir di sektor 2 telah keluar"
                + "\nNomor Plat " + plat[2] + " Parkir di sektor 3 telah keluar"
                + "\nNomor Plat " + plat[3] + " Parkir di sektor 4 telah keluar"
                + "\nNomor Plat " + plat[4] + " Parkir di sektor 5 telah keluar"
                + "\nNomor Plat " + plat[5] + " Parkir di sektor 6 telah keluar"
                + "\nNomor Plat " + plat[6] + " Parkir di sektor 7 telah keluar"
                + "\nNomor Plat " + plat[7] + " Parkir di sektor 8 telah keluar");
    }//GEN-LAST:event_tampilActionPerformed

    private void Masuk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk1ActionPerformed
        plat[0] = txtplat.getText().trim();
        Masuk1.setVisible(false);
        Keluar1.setVisible(true);
        tanggal[0] = d.format(c.getTime());

    }//GEN-LAST:event_Masuk1ActionPerformed

    private void Masuk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk2ActionPerformed
        plat[1] = txtplat.getText().trim();
        Masuk2.setVisible(false);
        Keluar2.setVisible(true);
        tanggal[1] = d.format(c.getTime());
    }//GEN-LAST:event_Masuk2ActionPerformed

    private void Keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar1ActionPerformed
        Keluar1.setVisible(false);
        Masuk1.setVisible(true);
        plat[0] = txtplat.getText().trim();
    }//GEN-LAST:event_Keluar1ActionPerformed

    private void Keluar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar3ActionPerformed
        Keluar3.setVisible(false);
        Masuk3.setVisible(true);
        plat[2] = txtplat.getText().trim();
    }//GEN-LAST:event_Keluar3ActionPerformed

    private void Keluar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar5ActionPerformed
        Keluar5.setVisible(false);
        Masuk5.setVisible(true);
        plat[4] = txtplat.getText().trim();
    }//GEN-LAST:event_Keluar5ActionPerformed

    private void Keluar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar6ActionPerformed
        Keluar6.setVisible(false);
        Masuk6.setVisible(true);
        plat[5] = txtplat.getText().trim();
    }//GEN-LAST:event_Keluar6ActionPerformed

    private void Masuk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk3ActionPerformed
        plat[2] = txtplat.getText().trim();
        Masuk3.setVisible(false);
        Keluar3.setVisible(true);
        tanggal[2] = d.format(c.getTime());
    }//GEN-LAST:event_Masuk3ActionPerformed

    private void Masuk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk4ActionPerformed
        plat[3] = txtplat.getText().trim();
        Masuk4.setVisible(false);
        Keluar4.setVisible(true);
        tanggal[3] = d.format(c.getTime());
    }//GEN-LAST:event_Masuk4ActionPerformed

    private void Keluar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar2ActionPerformed
        Keluar2.setVisible(false);
        Masuk2.setVisible(true);
        plat[1] = txtplat.getText().trim();
    }//GEN-LAST:event_Keluar2ActionPerformed

    private void Keluar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar4ActionPerformed
        Keluar4.setVisible(false);
        Masuk4.setVisible(true);
        plat[3] = txtplat.getText().trim();
    }//GEN-LAST:event_Keluar4ActionPerformed

    private void Masuk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk5ActionPerformed
        plat[4] = txtplat.getText().trim();
        Masuk5.setVisible(false);
        Keluar5.setVisible(true);
        tanggal[4] = d.format(c.getTime());
    }//GEN-LAST:event_Masuk5ActionPerformed

    private void Masuk6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk6ActionPerformed
        plat[5] = txtplat.getText().trim();
        Masuk6.setVisible(false);
        Keluar6.setVisible(true);
        tanggal[5] = d.format(c.getTime());
    }//GEN-LAST:event_Masuk6ActionPerformed

    private void Masuk7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk7ActionPerformed
        plat[6] = txtplat.getText().trim();
        Masuk7.setVisible(false);
        Keluar7.setVisible(true);
        tanggal[6] = d.format(c.getTime());
    }//GEN-LAST:event_Masuk7ActionPerformed

    private void Masuk8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk8ActionPerformed
        plat[7] = txtplat.getText().trim();
        Masuk8.setVisible(false);
        Keluar8.setVisible(true);
        tanggal[7] = d.format(c.getTime());
    }//GEN-LAST:event_Masuk8ActionPerformed

    private void Keluar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar7ActionPerformed
        Keluar7.setVisible(false);
        Masuk7.setVisible(true);
        plat[6] = txtplat.getText().trim();
    }//GEN-LAST:event_Keluar7ActionPerformed

    private void Keluar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Keluar8ActionPerformed
        Keluar8.setVisible(false);
        Masuk8.setVisible(true);
        plat[7] = txtplat.getText().trim();
    }//GEN-LAST:event_Keluar8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Park().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluar1;
    private javax.swing.JButton Keluar2;
    private javax.swing.JButton Keluar3;
    private javax.swing.JButton Keluar4;
    private javax.swing.JButton Keluar5;
    private javax.swing.JButton Keluar6;
    private javax.swing.JButton Keluar7;
    private javax.swing.JButton Keluar8;
    private javax.swing.JButton Masuk1;
    private javax.swing.JButton Masuk2;
    private javax.swing.JButton Masuk3;
    private javax.swing.JButton Masuk4;
    private javax.swing.JButton Masuk5;
    private javax.swing.JButton Masuk6;
    private javax.swing.JButton Masuk7;
    private javax.swing.JButton Masuk8;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTextArea nampil;
    private javax.swing.JLabel nomor;
    private javax.swing.JButton tampil;
    private javax.swing.JTextField txtplat;
    // End of variables declaration//GEN-END:variables
}
