/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanUAP;

import java.util.Date;

import java.awt.*;
import java.awt.event.*;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Rikza Priyudha
 */
public class SistemParkir extends javax.swing.JFrame {

    public static String Data[] = new String[16];
    public static String databanyak;
    Date sekarang = new Date();
    public static String Tampil[] = new String[1];

    /**
     * Creates new form SistemParkir
     */
    public SistemParkir() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PlatNomor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        A12 = new javax.swing.JButton();
        A22 = new javax.swing.JButton();
        A21 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B22 = new javax.swing.JButton();
        B21 = new javax.swing.JButton();
        C11 = new javax.swing.JButton();
        C12 = new javax.swing.JButton();
        C22 = new javax.swing.JButton();
        C21 = new javax.swing.JButton();
        D11 = new javax.swing.JButton();
        D12 = new javax.swing.JButton();
        D22 = new javax.swing.JButton();
        D21 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton10.setText("jButton2");

        jButton11.setText("jButton2");

        jButton12.setText("jButton2");

        jButton13.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setText("SISTEM PARKIR");

        jLabel2.setText("Nomor Plat : ");

        PlatNomor.setText(" ");
        PlatNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatNomorActionPerformed(evt);
            }
        });

        jButton1.setText("Tampilkan Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        A11.setText("Masuk");
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A11ActionPerformed(evt);
            }
        });

        A12.setText("Masuk");
        A12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A12ActionPerformed(evt);
            }
        });

        A22.setText("Masuk");
        A22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A22ActionPerformed(evt);
            }
        });

        A21.setText("Masuk");
        A21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A21ActionPerformed(evt);
            }
        });

        B11.setText("Masuk");
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });

        B12.setText("Masuk");
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });

        B22.setText("Masuk");
        B22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B22ActionPerformed(evt);
            }
        });

        B21.setText("Masuk");
        B21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B21ActionPerformed(evt);
            }
        });

        C11.setText("Masuk");
        C11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C11ActionPerformed(evt);
            }
        });

        C12.setText("Masuk");
        C12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C12ActionPerformed(evt);
            }
        });

        C22.setText("Masuk");
        C22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C22ActionPerformed(evt);
            }
        });

        C21.setText("Masuk");
        C21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C21ActionPerformed(evt);
            }
        });

        D11.setText("Masuk");
        D11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D11ActionPerformed(evt);
            }
        });

        D12.setText("Masuk");
        D12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D12ActionPerformed(evt);
            }
        });

        D22.setText("Masuk");
        D22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D22ActionPerformed(evt);
            }
        });

        D21.setText("Masuk");
        D21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D21ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\AKADEMIK\\PELAJARAN\\SEMESTER II\\Pemrograman Lanjut\\LATIHAN KODING\\Praktikum9\\src\\LatihanUAP\\UNIVERSITAS BRAWIJAYA LOGO.png")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jLabel4.setText("by: Rikza Priyudha Hirdad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(C11)
                                            .addComponent(C21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(C22)
                                            .addComponent(C12)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(A11)
                                            .addComponent(A21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(A22)
                                            .addComponent(A12))))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(B11)
                                            .addComponent(B21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B22)
                                            .addComponent(B12)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(D11)
                                            .addComponent(D21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(D22)
                                            .addComponent(D12)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PlatNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel4))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlatNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlatNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatNomorActionPerformed
        // TODO add your handling code here:a
    }//GEN-LAST:event_PlatNomorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // JOptionPane.showMessageDialog(null, Data[0] + "\n" + Data[1] + "\n" + Data[2] + "\n" + Data[3] + "\n" + Data[4] + "\n" + Data[5] + "\n"+ Data[6] + "\n" + Data[7] + "\n" + Data[8] + "\n" + Data[9] + "\n" + Data[10] + "\n" + Data[11] + "\n" + Data[12] + "\n"+ Data[13] + "\n" + Data[14] + "\n" + Data[15] + "\n");
        JOptionPane.showMessageDialog(null,
                Data[0] +"\n"
                + Data[1]+"\n"
                + Data[2]+"\n"
                + Data[3]+"\n"
                + Data[4]+"\n"
                + Data[5]+"\n"
                + Data[6]+"\n"
                + Data[7]+"\n"
                + Data[8]+"\n"
                + Data[9]+"\n"
                + Data[10]+"\n"
                + Data[11]+"\n"
                + Data[12]+"\n"
                + Data[13]+"\n"
                + Data[14]+"\n"
                + Data[15]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void A11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A11ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        
        
        if (A11.getText().equalsIgnoreCase("Masuk")) {
            Data[0] = "";
            String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[0] +=nopol;
            JOptionPane.showMessageDialog(null, Data[0] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            A11.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[0] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[0] = "";
            A11.setText("Masuk");
        }
        //a11
    }//GEN-LAST:event_A11ActionPerformed

    private void A12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A12ActionPerformed
        
        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        
        if (A12.getText().equalsIgnoreCase("Masuk")) {
            Data[1] = "";
            String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[1] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[1] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            A12.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[1] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[1] = "";
            A12.setText("Masuk");
        }
        //a12
    }//GEN-LAST:event_A12ActionPerformed

    private void A21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A21ActionPerformed
        
        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        Data[2] += String.valueOf(PlatNomor.getText().trim());
        if (A21.getText().equalsIgnoreCase("Masuk")) {
Data[2] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[2] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[2] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            A21.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[2] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[2] = "";
            A21.setText("Masuk");
        }
//a21
    }//GEN-LAST:event_A21ActionPerformed

    private void A22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A22ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        
        if (A22.getText().equalsIgnoreCase("Masuk")) {
Data[3] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[3] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[3] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            A22.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[3] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[3] = "";
            A22.setText("Masuk");
        }
//a22
    }//GEN-LAST:event_A22ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
       
        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (B11.getText().equalsIgnoreCase("Masuk")) {
Data[4] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[4] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[4] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            B11.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[4] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[4] = "";
            B11.setText("Masuk");
        }
    }//GEN-LAST:event_B11ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (B12.getText().equalsIgnoreCase("Masuk")) {
Data[5] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[5] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[5] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            B12.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[5] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[5] = "";
            B12.setText("Masuk");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_B12ActionPerformed

    private void B21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B21ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (B21.getText().equalsIgnoreCase("Masuk")) {
Data[6] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[6] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[6] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            B21.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[6] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[6] = "";
            B21.setText("Masuk");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_B21ActionPerformed

    private void B22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B22ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (B22.getText().equalsIgnoreCase("Masuk")) {
Data[7] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[7] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[7] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            B22.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[7] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[7] = "";
            B22.setText("Masuk");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_B22ActionPerformed

    private void C11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C11ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (C11.getText().equalsIgnoreCase("Masuk")) {
Data[8] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[8] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[8] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            C11.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[8] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[8] = "";
            C11.setText("Masuk");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_C11ActionPerformed

    private void C12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C12ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (C12.getText().equalsIgnoreCase("Masuk")) {
Data[9] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[9] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[9] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            C12.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[9] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[9] = "";
            C12.setText("Masuk");
        }// TODO add your handling code here:
    }//GEN-LAST:event_C12ActionPerformed

    private void C21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C21ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (C21.getText().equalsIgnoreCase("Masuk")) {
Data[10] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[10] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[10] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            C21.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[10] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[10] = "";
            C21.setText("Masuk");
        }// TODO add your handling code here:
    }//GEN-LAST:event_C21ActionPerformed

    private void C22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C22ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (C22.getText().equalsIgnoreCase("Masuk")) {
Data[11] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[11] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[11] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            C22.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[11] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[11] = "";
            C22.setText("Masuk");
        }// TODO add your handling code here:
    }//GEN-LAST:event_C22ActionPerformed

    private void D11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D11ActionPerformed
        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (D11.getText().equalsIgnoreCase("Masuk")) {
Data[12] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[12] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[12] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            D11.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[12] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[12] = "";
            D11.setText("Masuk");
        }// TODO add your handling code here:
    }//GEN-LAST:event_D11ActionPerformed

    private void D12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D12ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (D12.getText().equalsIgnoreCase("Masuk")) {
Data[13] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[13] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[13] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            D12.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[13] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[13] = "";
            D12.setText("Masuk");
        }// TODO add your handling code here:
    }//GEN-LAST:event_D12ActionPerformed

    private void D21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D21ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (D21.getText().equalsIgnoreCase("Masuk")) {
Data[14] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[14] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[14] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            D21.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[14] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[14] = "";
            D21.setText("Masuk");
        }// TODO add your handling code here:
    }//GEN-LAST:event_D21ActionPerformed

    private void D22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D22ActionPerformed

        String tgl = String.valueOf(sekarang.getDate());
        String bulan = String.valueOf(sekarang.getMonth());
        String tahun = String.valueOf(sekarang.getYear());
        String jam = String.valueOf(sekarang.getHours());
        String menit = String.valueOf(sekarang.getMinutes());
        if (D22.getText().equalsIgnoreCase("Masuk")) {
Data[15] = "";String nopol = String.valueOf(PlatNomor.getText().trim());
            Data[15] += String.valueOf(PlatNomor.getText().trim());
            JOptionPane.showMessageDialog(null, Data[15] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Parkir");
            PlatNomor.setText("");
            D22.setText("Keluar");
        } else {
            JOptionPane.showMessageDialog(null, Data[15] + "\n" + tgl + " " + bulan + " " + tahun + "-------" + jam + ":" + menit + "\nSedang Keluar");
            Data[15] = "";
            D22.setText("Masuk");
        }// TODO add your handling code here:
    }//GEN-LAST:event_D22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A11;
    private javax.swing.JButton A12;
    private javax.swing.JButton A21;
    private javax.swing.JButton A22;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B21;
    private javax.swing.JButton B22;
    private javax.swing.JButton C11;
    private javax.swing.JButton C12;
    private javax.swing.JButton C21;
    private javax.swing.JButton C22;
    private javax.swing.JButton D11;
    private javax.swing.JButton D12;
    private javax.swing.JButton D21;
    private javax.swing.JButton D22;
    private javax.swing.JTextField PlatNomor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
 class ActionTulisData implements ActionListener {

        public void actionPerformed(ActionEvent e) {

            Date sekarang = new Date();
            String hari = String.valueOf(sekarang.getDay());
            String tgl = String.valueOf(sekarang.getDate());
            String bulan = String.valueOf(sekarang.getMonth());
            String tahun = String.valueOf(sekarang.getYear());
            String jam = String.valueOf(sekarang.getHours());
            String menit = String.valueOf(sekarang.getMinutes());

        }
    }

}
